### ISSUE TITLE
type="email" allows invalid email addresses

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-input#214] opened 2022-11-03 17:34 UTC
## Describe the bug

When using auro-input with type="email", the validation considers an email address without a domain as valid

## To Reproduce

1. Create an auro-input type=email
1. Enter an email address without a domain such as jordan.chang@alaskaair
1. Tab away
1. Validation runs and throws no errors

## Expected behavior

Should display validation error

## Screenshots

![image](https://user-images.githubusercontent.com/3304352/199793766-476a5e2d-542c-44f9-9474-68e9663357c4.png)

**Comment by blackfalcon** [comment] 2022-11-03 18:59
This is not a bug. The element is performing as expected. 

The code we use for validation is based on the default HTML email validation in the client. You can test that here https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_email

That being said, we can consider a new feature to make this more robust [regex](https://mailtrap.io/blog/html5-email-validation-tutorial/) solution. But this also opens us up to other potential issues. 

The team can take this away and consider these options with the upcoming re-architecture of the input element. 

- https://github.com/AlaskaAirlines/auro-input/issues/210

**Comment by blackfalcon** [comment] 2023-01-19 00:18
Closing this issue as there is no work to be done at this time. This issue has been linked to upcoming work with refactoring the input element and will be revisited.

**Closed by blackfalcon** 2023-01-19 00:18 UTC
Labels: auro-input
