### ISSUE TITLE
icon attribute position is incorrect on non bordered auro-input

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-input#201] opened 2022-10-12 19:43 UTC
## Describe the bug

Icon type icons appearing on the left of the input have incorrect positioning on non-bordered auro-inputs.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/input
1. Scroll down to second Credit Card example
1. See error

## Expected behavior

Positioning of icon should be even with the input text.

## Screenshots

Error:
<img width="465" alt="Screen Shot 2022-10-12 at 12 09 20 PM" src="https://user-images.githubusercontent.com/55807669/195433583-89228d6f-0a3d-466d-a128-396d8a5aa08e.png">

Expected:
![Screen Shot 2022-10-12 at 1 08 18 PM](https://user-images.githubusercontent.com/55807669/195437859-94aeff75-060f-4265-bb63-386d9a4c29b7.png)

**Comment by blackfalcon** [comment] 2022-10-13 17:09
@leeejune please provide @jordanjones243 design instructions as to the placement of the icon for the non-bordered input with no value.

**Comment by blackfalcon** [comment] 2022-10-13 17:11
@leeejune please reassign this issue back to @jordanjones243 once completed with the design work.

**Comment by jordanjones243** [comment] 2022-10-21 21:28
This ticket is not actively being worked on. Fixing the position is an easy fix, but was coupled in a repo that also had the goal of fixing the sizing of label and input text under all input scenarios. After further discussion, we decided we were going to head towards a re-design of `auro-input` and to put these fixes on hold for the time being.

**Comment by blackfalcon** [comment] 2022-10-24 16:22
Adding the BLOCKED label as this work will be predicated on decisions made with the following issue 

- https://github.com/AlaskaAirlines/auro-input/issues/205

**Comment by blackfalcon** [comment] 2023-01-20 20:15
Seeing that this issue is blocked and knowing what is live in production, I am wondering if we can make a simple change that would remove any weird issues. 

What if we just made the spacing above the label consistent with the bordered version? @leeejune 

![Screen Shot 2023-01-20 at 12 13 45 PM](https://user-images.githubusercontent.com/181089/213797409-6a60b15e-a9ae-4e02-86ab-7d495f0d21a6.png)

**Comment by leeejune** [comment] 2023-01-20 22:10
@blackfalcon If we were to make that change, what would happen to the input text that appears once the user clicks into the input field? Also, the right spacing of the icon in the screenshot seems to be off–don't know if that's just temporary.

**Comment by blackfalcon** [comment] 2023-01-20 23:38
There was work done in the past that normalized much of the input layout. As a result, the icon is now floating. See the screen shot from Auro below. 

![Screen Shot 2023-01-20 at 3 37 18 PM](https://user-images.githubusercontent.com/181089/213823915-631ac90d-c8c9-41ba-930d-ddb28b92525e.png)

The fix I am requesting is what is shown in the screen shot in the previous comment. The request does not move the icon, but locates the label to the same place as with the bordered version and the animation works the same way.

**Comment by leeejune** [comment] 2023-01-21 00:56
<img width="338" alt="Screen Shot 2023-01-20 at 4 49 51 PM" src="https://user-images.githubusercontent.com/55998746/213830227-b1feac86-087e-414a-b01b-2707c19e33b3.png">

I understand, but I meant what it would look like if it is filled as shown in the screenshot. I will explore spacing options and reply again.

**Comment by blackfalcon** [comment] 2023-01-24 18:12
@june is reaching out to the rest of the design team for feedback on a proposed direction.

**Comment by leeejune** [comment] 2023-01-31 23:52
Designers confirmed of the change in padding. What are the next steps @blackfalcon?

**Comment by jason-capsule42** [comment] 2023-02-21 21:41
Current screenshot from localhost of this branch.

<img width="553" alt="Screenshot 2023-02-21 at 1 41 01 PM" src="https://user-images.githubusercontent.com/23223137/220464923-a1a66498-a4c9-45a2-b220-462d843fbfbb.png">

**Closed** 2023-02-21 21:47 UTC
Labels: Type: Bug, Type: Design, auro-input
